<template>
	<div class="container p-3" fluid>
		<p><span style="background-color: #aaaa00; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem;">tag <span style="color: #eeffff; background-color: #003333; border-radius: 0.4rem; padding: 0.4rem; margin-right: 0;">text</span></span></p>
		<p><span style="background-color: #aaaa00; padding: 0.4rem; padding-left: 0; padding-right: 0.4rem; border-radius: 0.4rem;"><span style="color: #eeffff; background-color: #003333; border-radius: 0.4rem; padding: 0.4rem; margin-left: 0;">text</span> tag</span></p>
		<p><span style="background-color: #aaaa00; padding: 0.4rem; padding-left: 0; padding-right: 0.4rem; border-radius: 0.4rem;"><span style="color: #eeffff; background-color: #003333; border-radius: 0.4rem; padding: 0.4rem; margin-left: 0;"><font-awesome-icon icon="exclamation-triangle" fixed-width/></span> text</span></p>
		<p><span style="background-color: #aaaa00; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem;">tag <span style="color: #eeffff; background-color: #003333; border-radius: 0.4rem; padding: 0.4rem; margin-right: 0;"><font-awesome-icon icon="exclamation-triangle" fixed-width/></span></span></p>
		<p><span style="background-color: #aaaa00; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem;"><font-awesome-icon icon="exclamation-triangle" fixed-width/> <span style="color: #eeffff; background-color: #003333; border-radius: 0.4rem; padding: 0.4rem; margin-right: 0;">text</span></span></p>
		<p><span style="background-color: #aaaa00; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem;"><font-awesome-icon icon="exclamation-triangle" fixed-width/> <span style="color: #eeffff; background-color: #003333; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0;">text</span></span></p>
		<p><span style="background-color: #dd1c1a; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="exclamation-triangle" fixed-width style="margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #262626; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">text</span></span></p>
		<p><span style="background-color: #11a53c; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="exclamation-triangle" fixed-width style="margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #262626; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">validates</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="check" fixed-width style="color: #11a53c; margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #262626; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">validates</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="check" fixed-width style="color: #11a53c; margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #46494c; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">validates</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="check" fixed-width style="color: #b3001b; margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #46494c; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">validates</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="check" fixed-width style="color: #dd1c1a; margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #46494c; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">validates</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #007fad; margin-right: 0.4rem;"/> <span style="color: #e5f2f7; background-color: #46494c; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #004f79; margin-right: 0.4rem;"/> <span style="color: #e5f2f7; background-color: #46494c; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #e5f2f7; margin-right: 0.4rem;"/> <span style="color: #e5f2f7; background-color: #46494c; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #0092c7; margin-right: 0.4rem;"/> <span style="color: #e5f2f7; background-color: #46494c; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>

		<p><span style="background-color: #46494c; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #007fad; margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #262626; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>
		<p><span style="background-color: #eeeeee; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #007fad; margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #262626; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>
		<p><span style="background-color: #eeeeee; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #007fad; margin-right: 0.4rem;"/> <span style="color: #eeffff; background-color: #003333; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>
		<p><span style="background-color: #262626; padding: 0.4rem; padding-right: 0; border-radius: 0.4rem; font-size: small;"><font-awesome-icon icon="external-link-alt" fixed-width style="color: #007fad; margin-right: 0.4rem;"/> <span style="color: #003333; background-color: #eeeeee; border-radius: 0 0.4rem 0.4rem 0; padding: 0.4rem; margin-right: 0; font-weight: bold;">etsin</span></span></p>

	</div>
</template>

<script>
export default {}
</script>
