export default {
	'TabSelector': require('./TabSelector.vue').default,
	'SchemaString': require('./String.vue').default,
	'SchemaNumber': require('./Number.vue').default,
	'SchemaObject': require('./Object.vue').default,
	'SchemaArray': require('./Array.vue').default,
	'SchemaInlineArray': require('./InlineArray.vue').default,
	'SchemaAnyOf': require('./anyOf.vue').default,
	'SchemaAllOf': require('./allOf.vue').default,
	'SchemaOneOf': require('./oneOf.vue').default,
	'SchemaEnum': require('./Enum.vue').default,
	'widget-googlemaps': require('./widget-googlemaps.vue').default,
	'refdata-list': require('./refdata/list.vue').default,
	'reference-data': require('../components/ReferenceData/ReferenceData.vue').default,
	'i18n-string': require('./i18n-string/i18n-string.vue').default,
	'i18n-textarea': require('./i18n-string/i18n-textarea.vue').default,
	'tabbed-array': require('./TabbedArray.vue').default,
	'autocomplete': require('./refdata/autocomplete.vue').default,
	'browser': require('../filebrowser/filebrowser.vue').default,
}
