export default {
	'schema-tab-selector': require('./v-schema-tab-selector.vue').default,
	'schema-string': require('./v-schema-string.vue').default,
	'schema-number': require('./v-schema-number.vue').default,
	'schema-object': require('./v-schema-object.vue').default,
	'schema-array': require('./v-schema-array.vue').default,
	'schema-inline-array': require('./v-schema-inline-array.vue').default,
	'schema-anyof': require('./v-schema-anyof.vue').default,
	'schema-allof': require('./v-schema-allof.vue').default,
	'schema-enum': require('./v-schema-enum.vue').default,
	'widget-googlemaps': require('./widget-googlemaps.vue').default,
	'refdata-list': require('./refdata/list.vue').default,
	'reference-data': require('../components/ReferenceData/ReferenceData.vue').default,
	'i18n-string': require('./i18n-string/i18n-string.vue').default,
	'i18n-textarea': require('./i18n-string/i18n-textarea.vue').default,
	'tabbed-array': require('./TabbedArray.vue').default,
	'autocomplete': require('./refdata/autocomplete.vue').default,
	'browser': require('../filebrowser/filebrowser.vue').default,
	'date-range': require('../components/DateRange.vue').default,
}
